List<Map<String, dynamic>> bags = [
    {'id' : 'b1',
      'name': 'Tote Bag',
      'price': 50,
      'color': 'Black',
      'size': 'Medium',
      'material': 'Leather',
      'design': 'Classic',
      'brand': 'ABC Company',
    },
    {'id' : 'b2',
      'name': 'Shoulder Bag',
      'price': 65,
      'color': 'Brown',
      'size': 'Small',
      'material': 'Faux Leather',
      'design': 'Casual',
      'brand': 'XYZ Brand',
    },
    {'id' : 'b3',
      'name': 'Crossbody Bag',
      'price': 40,
      'color': 'Red',
      'size': 'Small',
      'material': 'Nylon',
      'design': 'Sporty',
      'brand': 'DEF Accessories',
    },
    {'id' : 'b4',
      'name': 'Clutch',
      'price': 80,
      'color': 'Silver',
      'size': 'Small',
      'material': 'Metallic',
      'design': 'Elegant',
      'brand': 'GHI Fashion',
    },
    {'id' : 'b5',
      'name': 'Backpack',
      'price': 55,
      'color': 'Blue',
      'size': 'Large',
      'material': 'Canvas',
      'design': 'Urban',
      'brand': 'JKL Outdoors',
    },
        {'id' : 'b6',
      'name': 'Satchel',
      'price': 75,
      'color': 'Beige',
      'size': 'Medium',
      'material': 'Faux Leather',
      'design': 'Sophisticated',
      'brand': 'MNO Collection',
    },
    {'id' : 'b7',
      'name': 'Bucket Bag',
      'price': 60,
      'color': 'Pink',
      'size': 'Small',
      'material': 'Suede',
      'design': 'Bohemian',
      'brand': 'PQR Accessories',
    },
    {'id' : 'b8',
      'name': 'Wristlet',
      'price': 35,
      'color': 'Gold',
      'size': 'Small',
      'material': 'Metallic',
      'design': 'Chic',
      'brand': 'STU Fashion',
    },
    {'id' : 'b9',
      'name': 'Tote Backpack',
      'price': 90,
      'color': 'Gray',
      'size': 'Large',
      'material': 'Leather',
      'design': 'Versatile',
      'brand': 'VWX Outdoors',
    },
    {'id' : 'b10',
      'name': 'Evening Clutch',
      'price': 55,
      'color': 'Black',
      'size': 'Small',
      'material': 'Velvet',
      'design': 'Glamorous',
      'brand': 'YZ Accessories',
    },
    // Add more bag maps here...
  ];
