List<Map<String, dynamic>> fragrance = [
    { 'id' : 'f1',
      'name': 'Floral Bouquet',
      'price': 100,
      'scent': 'Floral',
      'size': '50 ml',
      'ingredients': ['Rose', 'Jasmine', 'Lily of the Valley'],
      'longevity': 'Medium',
      'brand': 'ABC Perfumes',
            'quantity' : 36
    },
    {'id' : 'f2',
      'name': 'Citrus Zest',
      'price': 80,
      'scent': 'Citrus',
      'size': '30 ml',
      'ingredients': ['Orange', 'Lemon', 'Bergamot'],
      'longevity': 'Long',
      'brand': 'XYZ Fragrances',
            'quantity' : 89
    },
    {'id' : 'f3',
      'name': 'Oriental Spice',
      'price': 120,
      'scent': 'Oriental',
      'size': '100 ml',
      'ingredients': ['Vanilla', 'Cinnamon', 'Amber'],
      'longevity': 'Long',
      'brand': 'PQR Fragrances',
            'quantity' : 28
    },
    {'id' : 'f4',
      'name': 'Fresh Breeze',
      'price': 90,
      'scent': 'Fresh',
      'size': '50 ml',
      'ingredients': ['Bergamot', 'Green Tea', 'Mint'],
      'longevity': 'Medium',
      'brand': 'LMN Perfumes',
            'quantity' : 10
    },
    {'id' : 'f5',
      'name': 'Woody Serenade',
      'price': 150,
      'scent': 'Woody',
      'size': '75 ml',
      'ingredients': ['Cedarwood', 'Sandalwood', 'Patchouli'],
      'longevity': 'Long',
      'brand': 'RST Scents',
            'quantity' : 30
    },
    {'id' : 'f6',
      'name': 'Romantic Blossoms',
      'price': 110,
      'scent': 'Floral',
      'size': '30 ml',
      'ingredients': ['Rose', 'Peony', 'Magnolia'],
      'longevity': 'Medium',
      'brand': 'UVW Perfumery',
            'quantity' : 20
    },
    {'id' : 'f7',
      'name': 'Aquatic Splash',
      'price': 95,
      'scent': 'Aquatic',
      'size': '50 ml',
      'ingredients': ['Sea Breeze', 'Water Lily', 'Musk'],
      'longevity': 'Medium',
      'brand': 'XYZ Scents',
            'quantity' : 12
    }

];