List<Map<String, dynamic>> jewelry = [
  {
    'name': 'Diamond Pendant',
    'price': 500,
    'style': 'Classic',
    'size': 'Small',
    'material': 'Gold',
    'finish': 'Polished',
    'brand': 'ABC Jewelers',
  },
  {
    'name': 'Silver Hoop Earrings',
    'price': 50,
    'style': 'Minimalist',
    'size': 'Medium',
    'material': 'Silver',
    'finish': 'Matte',
    'brand': 'XYZ Accessories',
  },
  {
    'name': 'Pearl Necklace',
    'price': 350,
    'style': 'Elegant',
    'size': 'Medium',
    'material': 'Pearl',
    'finish': 'Glossy',
    'brand': 'PQR Jewelers',
  },
  {
    'name': 'Rose Gold Bracelet',
    'price': 180,
    'style': 'Trendy',
    'size': 'Small',
    'material': 'Rose Gold',
    'finish': 'Polished',
    'brand': 'LMN Accessories',
  },
  {
    'name': 'Sapphire Ring',
    'price': 650,
    'style': 'Statement',
    'size': 'Large',
    'material': 'White Gold',
    'finish': 'Sparkling',
    'brand': 'RST Gems',
  },
  {
    'name': 'Silver Charm Bracelet',
    'price': 90,
    'style': 'Charming',
    'size': 'Medium',
    'material': 'Silver',
    'finish': 'Textured',
    'brand': 'UVW Jewels',
  },
  {
    'name': 'Diamond Stud Earrings',
    'price': 800,
    'style': 'Classic',
    'size': 'Small',
    'material': 'White Gold',
    'finish': 'Polished',
    'brand': 'XYZ Jewelers',
  },
  {
    'name': 'Emerald Pendant',
    'price': 550,
    'style': 'Luxurious',
    'size': 'Small',
    'material': 'Gold',
    'finish': 'Polished',
    'brand': 'ABC Jewels',
  },
  {
    'name': 'Diamond Tennis Bracelet',
    'price': 1200,
    'style': 'Elegant',
    'size': 'Medium',
    'material': 'White Gold',
    'finish': 'Shiny',
    'brand': 'XYZ Luxury',
  },
  {
    'name': 'Ruby Stud Earrings',
    'price': 450,
    'style': 'Timeless',
    'size': 'Small',
    'material': 'Yellow Gold',
    'finish': 'Polished',
    'brand': 'PQR Gems',
  },
  {
    'name': 'Silver Cuff Bangle',
    'price': 150,
    'style': 'Modern',
    'size': 'Medium',
    'material': 'Silver',
    'finish': 'Brushed',
    'brand': 'LMN Jewelry',
  },
  {
    'name': 'Amethyst Cocktail Ring',
    'price': 380,
    'style': 'Statement',
    'size': 'Large',
    'material': 'Sterling Silver',
    'finish': 'Glossy',
    'brand': 'RST Designs',
  }
];
